server:
  port: 8880

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/xjt_springboot_demos?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    port: 6379
    host: 127.0.0.1

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.xjt.redis.domain
